### ISSUE TITLE
specbloc not found

### ISSUE THREAD

**Issue by JasperGeissler** [Bhattacharya-Lab/PIQLE#1]
Hello!

I was trying to perform a docking analysis between two proteins and I keep running into the error that the corresponding specbloc file of the first a3m file isn't found. How can I remedy this?

Best,
Jasper

**Comment by mhshuvo1** [comment]
The taxonomy database is required to process the multiple sequence alignment. Please download the updated “config.py” to PIQLE’s root directory and reconfigure PIQLE ($python config.py). It will download the database to the designated directory. Afterward, you can run PIQLE for testing.

**Comment by JasperGeissler** [comment]
> The taxonomy database is required to process the multiple sequence alignment. Please download the updated “config.py” to PIQLE’s root directory and reconfigure PIQLE ($python config.py). It will download the database to the designated directory. Afterward, you can run PIQLE for testing.

Thank you for the swift reply. Unfortunately despite downloading the new configuration script, the code still returns the same error, and only for the first .a3m alignment file. I also noticed the script doesn't stop running despite returning the error of the missing .specbloc. Would there be another remedy?

**Comment by mhshuvo1** [comment]
After you download the new configuration script, you need to reconfigure PIQLE by running the config.py script from PIQLE’s root directory as mentioned earlier ($python config.py). After you successfully reconfigure PIQLE, please make sure you can see the database called “tax_tree” under apps/glinter.

**Comment by JasperGeissler** [comment]
I have verified the presence of the file "tax_tree" with a size of approximately 223MB in apps/glinter. Unfortunately the error keeps repeating itself. Is there no other solution outside of rerunning the config.py script?

**Comment by mhshuvo1** [comment]
Please run the example command to check the installation. Additionally, you may perform a fresh installation. If the issue persists, please let us know with the error log.

**Comment by JasperGeissler** [comment]
I have run the example command to check the installation and the error still persists. Through the example command more information was returned compared to with my own, but according to output some species couldn't be found, and the .a3m specbloc still cannot be found. Please find attached the output on the terminal.

[piqle_errorlog.txt](https://github.com/Bhattacharya-Lab/PIQLE/files/10919505/piqle_errorlog.txt)

**Comment by mhshuvo1** [comment]
Looks like a permission-related issue. Please make sure the executables under the “apps/glinter/external/” directory have execute permission. To further check, you may run the following two commands sequentially to see if you can generate a “.specbloc”,
$ ./apps/glinter/external/A3M_NoGap example/msa/example_A.a3m example_A.nogap
$./apps/glinter/external/A3M_SpecBloc example_A.nogap apps/glinter/tax_tree example_A.specbloc
If you can generate “example_A.specbloc” without any issues, you should not encounter the “.specbloc” generation issue while running PIQLE. You may then check your command to see if you are passing the paths to input files correctly.
